### ISSUE TITLE
Beeware tutorial: Toga TextInput in iOS

### ISSUE THREAD

**Issue by Skifarer** [beeware/toga#1493]
Caveat: I am very, ***very*** new to this, so sorry if this is just me being thick!!

I've run through the tutorial through to the iOS portion, and am able to create and build the project OK. However, when I try to run the project with `briefcase run iOS`, I'm presented with a set of error messages, as follows:

```
Exception ignored on calling ctypes callback function: <function objc_property.class_register.<locals>._objc_getter at 0x12ffd6560>
Traceback (most recent call last):
File "/Users/.../Hello World.app/Library/Application Support/com.example.helloworld/app_packages/rubicon/objc/api.py", line 434, in _objc_getter
value = value.value
ValueError: PyObject is NULL
```

The app.py file looks like the version in step 2 of the tutorial:

```
class HelloWorld(toga.App):
    def startup(self):
        main_box = toga.Box(style=Pack(direction=COLUMN))

        name_label = toga.Label(
            'Your name: ',
            style=Pack(padding=(0, 5))
        )
        self.name_input = toga.TextInput(style=Pack(flex=1))

        name_box = toga.Box(style=Pack(direction=ROW, padding=5))
        name_box.add(name_label)
        name_box.add(self.name_input)

        button = toga.Button(
            'Say Hello!',
            on_press=self.say_hello,
            style=Pack(padding=5)
        )

        main_box.add(name_box)
        main_box.add(button)

        self.main_window = toga.MainWindow(title=self.formal_name)
        self.main_window.content = main_box
        self.main_window.show()

    def say_hello(self, widget):
        print("Hello,", self.name_input.value)
```

I eventually traced the issue back to the `toga.TextInput` call - the app ran fine with this line not included (and the corresponding `name_box.add(self.name_input)` call, obviously). Digging a bit deeper, I managed to get the text input box to appear and (apparently) function correctly in iOS by commenting out the `self.native.impl` call from toga_iOS/widgets/textinput.py:

```
class TextInput(Widget):
    def create(self):
        self.native = TogaTextField.new()
        self.native.interface = self.interface
        #self.native.impl #Commented out this line!!!
        
        self.native.borderStyle = UITextBorderStyle.RoundedRect
        
        self.native.addTarget(
            self.native,
            action=SEL('textFieldDidChange:'),
            forControlEvents=UIControlEventEditingChanged
        )

        # Add the layout constraints
        self.add_constraints()
```
I'm not sure what this does, but it seems to get it to work! I presume, however, this should not be necessary, and the toga.TextInput control should probably work straight out of the box, as it were...

**Environment:**
 - Operating System: macOS Monterey 12.3.1, MacBook Pro (13-inch, M1, 2020)
 - Python version: 3.10.0
 - Software versions:
   - Briefcase: 0.3.6
   - Toga: toga_iOS-0.3.0.dev33
   - Rubicon: rubicon_objc-0.4.2-py3.10

**Comment by freakboy3742** [comment]
Thanks for the report! You're not being thick at all - you've found a bug that slipped into the dev33 release. The good news is that we've already fixed it in #1492.

**Comment by Skifarer** [comment]
Thanks for the speedy response!! I assumed it must have been something minor like that, but managed to not stumble across #1492 on my travels. It's still not working for me, but I suspect that's more to do with my lack of experience with pip/git etc and not having the latest version. Thanks again!
