### ISSUE TITLE
'app' property not always applied to contents of containers

### ISSUE THREAD

**Issue by Bobw147** [beeware/toga#833]
## Expected Behavior
When a widget is added to another widget the 'app' property should be applied to it and all of its descendants

## Current Behavior
(See example below)
1) Add content to a container 
2) Add the container to the main window
3) The 'app' property of the containers content is set to None

The setting of the 'app' property is not propagated down the widgets that form the content of the container.

This appears to be because when the container widget has its own 'app' property set it invokes the 'app' property setter of the base widget class. This propagates the setting of the 'app' property down the widgets children but because some containers (e.g. SplitContainer) use 'content' rather than children this propagation does not take place.

## Steps to reproduce
        canvas = toga.Canvas(style=Pack(flex=1))
        box = toga.Box(children=[canvas])

        left_panel = Button('Left panel Button')
        right_panel = box

        # Setting the content of the SplitContainer before it is added to the main window
        # results in the 'app' property of it's content not being set
        split_container = SplitContainer(style=Pack(flex=1), content=[left_panel, right_panel])
 
        self.main_window = MainWindow(title=self.formal_name)
        self.main_window.content = split_container
        self.main_window.show()

## Your Environment

* Python Version (list the specific version number)

* Operating System and Version (select from the following and list the specific version number; if your OS is not listed, list that as well)

  - [ x] macOS - version:
  - [ ] Linux - distro:   - version:
  - [ ] Windows - version:
  - [ ] Other - name:  - version:

* Toga Version (list the specific version number or git hash)
Toga 0.3.0 dev 19

* Toga Target (the type of app you are trying to generate)

  - [ ] android
  - [ x] cocoa
  - [ ] django
  - [ ] gtk
  - [ ] iOS
  - [ ] tvOS
  - [ ] watchOS
  - [ ] winforms
  - [ ] win32
  - [ ] Other (please specify)

**Comment by freakboy3742** [comment]
This looks like an accidental oversight; but I agree that the `app` property should be applied to children, no matter how they're added.

**Comment by SamSchott** [comment]
This is one of the changes in PR #814 which is part of API to insert and remove children.

**Comment by Bobw147** [comment]
Currently testing a fix for this

**Comment by Bobw147** [comment]
This issue does not appear to have been fixed as part of #814 so I have restarted work on it based on my earlier investigation. The following code snippets highlight the source of the problem.

The following code from toga/window.py shows what happens when a widget is assigned to the window.

   ' @content.setter
    def content(self, widget):
        # Assign the content widget to the same app as the window.
        widget.app = self.app

        # Assign the content widget to the window.
        widget.window = self

        # Track our new content
        self._content = widget

        # Manifest the widget
        self._impl.set_content(widget._impl)

        # Update the geometry of the widget
        widget.refresh()
'
The line:
       ' widget.app = self.app'

invokes the following code in the widget class in toga/base.py

`  @app.setter
    def app(self, app):
        # raise an error when we already have an app and attempt to override it
        # with a different app
        if self._app and app and self._app != app:
            raise ValueError("Widget %s is already associated with an App" % self)

        elif self._impl:
            self._app = app
            self._impl.set_app(app)
            for child in self.children:
                child.app = app
`
This fails when the widget being added to the window (or any other content holder) is an OptionContainer, ScrollContainer or SplitContainer as these do not support the self.children attribute. Instead they use self.content so the recursive descent algorithm within base.py cannot proceed any further.

There a number of solutions to this problem including the following.

1. Modify the algorithm in base.py so that it also checks to see if the current widget has a 'self._content' attribute and if so set the app attribute on its content widgets.
2. Modify the algorithm in base.py to invoke a self._set_app method which performs the recursive descent on self.children but is overridden in the above containers to perform the same action on self.content. 
3. Modify the structure of the container objects so that they add their content to self.children instead of self.content. The content attribute can be maintained for backwards compatibility but would return self.children instead of self.content

There may be other solutions that people would like to propose but these are the only ones that have occurred to me so far.

Of these I would discount #1 immediately as it is little more than an untidy hack.
#2 is much more in keeping with the current design principles in that it mimics the use of self._set_window. This makes it a much tidier solution.
#3 is more intrusive but would be my preferred solution for the reason outlined below..

The current structure of adding widgets to some containers as content rather than children means that they do not appear directly in the widget node tree. There is an internal inconsistency here because the Box container DOES use children rather than content. What is the reason for this  difference? My preference would be for a node tree that fully and truly represents the structure of the widget layout without indirection.

**Comment by Bobw147** [comment]
It seems that #814 did not provide a fix for this so I am reopening my investigation and picking up where I left off. I have identified the cause but before I go any further there is something I would like to understand a little better.

Is there a functional reason why OptionContainer, ScrollContainer and SplitContainer use content while Box and other widgets use children?

I ask because this is at the heart of the issue and I need to understand the rationale behind it in order to determine what the realistic solutions are.

**Comment by SamSchott** [comment]
You are right, #814 does not fix the issue. In hindsight, I even forgot why I thought that it does.

I did not come up with the concept of "content" in toga but maybe I can try to explain its distinction from children, for my benefit as well as yours. I have been very confused about it while writing #814, which probably contributed to my wrong promise. @freakboy3742 can correct me if the given explanation is wrong.

A "container" is the top-level widget in which all children are laid out. In the native layer, every view is added as a subview to the container, regardless of where it is in toga's widget hierarchy. For instance, in case of multiple nested Boxes, the top-level Box would be the container for all children. Within such a container, toga itself handles calculating the constraints and laying out the children. Such a container can then be the "content" of a window. 

Widgets can have "content" as well if they have subviews which are not statically laid out by toga but rather adapt their position or visibility on screen according to user input (scrolling, resizing a split view, etc). Within this subview, the layout is again controlled by toga directly.

Therefore, every widget which is "content" (of a window or another widget) has its own viewport and its container is `None`. On the other hand, every child has a top level "container" and no viewport.

**Comment by Bobw147** [comment]
Thanks for that explanation Sam. I had to read it a few times for it to sink in but am pretty sure I understand the gist of it now. I must confess that I have an alarm bell ringing in my mind which I can't quite get to the root of. It seems to be associated with the idea that the tree structure is a layout issue which means that the core is designed around or interspersed with layout details which should surely be the sole responsibility of styling. This is somewhat supported by the realisation that the Node class has a "refresh()" method that descends the node tree from the given root. This again is binding the tree structure to layout/styling in a manner I wouldn't have expected. This is all moving away from the scope of this original issue but it was the failure to correctly set the app attribute that led me down this path. The current structure is going to complicate matters when the time comes to integrate Colosseum into Toga. I know this as a fact because I have already done a little bit of background work on it!

I suspect @freakboy3742 will disagree but I think this area of the core could do with better partitioning between physical structure (the node tree) and layout (physical size and positioning of widgets via styling).
